Set default php version
dincho/pagrant pull request #38
Opened 2018-11-19 09:39 UTC by KristiyanHristov

When you re-provision with a changed php-fpm version you will end up with multiple php versions.
This task ensures that you are using the new version.

2018-11-19 12:48 UTC, venimus requested changes

2018-11-19 12:48 UTC, venimus commented on ansible/app.yml
> +    - name: Set default PHP version
this should be in setup.yml

2018-11-19 13:07 UTC, KristiyanHristov commented on ansible/app.yml
> +    - name: Set default PHP version
Do you mean `service.yml`?

2018-11-19 13:35 UTC, venimus commented on ansible/app.yml
> +    - name: Set default PHP version
yes

2018-11-20 09:22 UTC, KristiyanHristov commented on ansible/app.yml
> +    - name: Set default PHP version
2920aff

2018-11-20 10:17 UTC, venimus approved these changes

2018-11-20 11:05 UTC, dincho approved these changes

2018-11-20 11:10 UTC, merged