Prioritize execution of custom tasks
dincho/pagrant pull request #42
Opened 2020-02-10 15:49 UTC by KristiyanHristov

Running user defined tasks before the built in ones (bower, composer install) can resolve missing dependencies.

For example:
Composer packages might require an apt-package that is missing from the default config.

2020-02-11 14:05 UTC, dincho approved these changes

2020-02-11 22:24 UTC, IvayloPapazov approved these changes

2020-02-12 16:50 UTC, KristiyanHristov commented
Let's discuss it some more. I think there is both the need for user defined pre and post tasks.

2020-02-12 16:50 UTC, KristiyanHristov commented
Also these changes should revert #41

2020-02-13 07:46 UTC, venimus commented on ansible/app.yml
> +      when: projecttasks.stat.exists == True
== true?

2020-02-13 07:57 UTC, venimus commented
IMHO this stat thing is not ok
Better alternative is
```
tasks:
    - include: "{{ item }}"
      tags: projecttasks
      with_first_found:
        - files:
            - "{{ project_path }}/ansible_dev.yml"
          skip: true
```

Or even (however I expect this one to mute the failures in the included tasks, didn't test it):
```
- include: "{{ project_path }}/ansible_dev.yml"
   tags: projecttasks
   failed_when: false
```

2020-02-13 08:00 UTC, venimus requested changes
You already edited the whole block, better refactor it, see [pr comment](https://github.com/dincho/pagrant/pull/42#issuecomment-585599005)

2020-02-13 09:42 UTC, venimus commented
About the problem
I think you can create 'after' task with `notify: after tasks` which could be used in the included file. So you can have a way to define tasks that run after the main stuff
https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html#handlers-running-operations-on-change
```
tasks:
    - include ansibe_dev.yml
...
    - name: notify handlers before main tasks
      command: echo "this task will run after"
      notify: "after tasks"
```

in the `ansible_dev.yml`
```
tasks:
    - name: stop something before tasks
      tasks: [...]

handlers:
    - name: start something after tasks
      tasks: [...]
      listen: "after tasks"

```

2020-03-10 08:37 UTC, KristiyanHristov commented
I would close this in favor of #43

2020-03-20 13:28 UTC, closed without merging