Make npm, bower and composer install optional
dincho/pagrant pull request #43
Opened 2020-03-10 08:36 UTC by KristiyanHristov

- Makes apt packages configurable
- Makes npm packages configurable
- Disabling initial install of npm, bower or composer packages allows for custom task ordering

2020-03-10 08:37 UTC, KristiyanHristov commented
README should be updated

2020-03-13 10:17 UTC, venimus commented on ansible/services.yml
>      - name: Install nodejs, git, make
This will be no more relevant

2020-03-13 10:18 UTC, venimus commented on ansible/services.yml
> +      - nodejs
I don't think nodejs should be here

2020-03-13 10:19 UTC, venimus commented on ansible/services.yml
> +    has_npm: true
There should be dedicated nodejs + npm install

2020-03-13 10:22 UTC, venimus commented on ansible/services.yml
>      - name: Install bower & yarn
install npm packages

2020-03-16 14:37 UTC, KristiyanHristov commented on ansible/services.yml
> +        - unzip
I don't pass pass an array directly to handle this case: (a downgraded package) 

```
apt_packages:
      - { name: nodejs, state: present }
      - { name: git, state: present }
      - { name: make, state: present }
      - { name: unzip, state: present }
      - { name: php-ast=0.1.6-1, dpkg_options: "force-confdef,force-confold,force-downgrade", state: present }
```

2020-03-16 14:56 UTC, venimus requested changes

2020-03-16 14:56 UTC, venimus commented on README.md
> +        - npm
put the defaults here (and mention it as comment)
This is designed to be copy-pasted so don't break that

2020-03-16 14:56 UTC, venimus commented on README.md
> +        - npm
In fact better make different section for it

2020-03-17 08:51 UTC, venimus approved these changes

2020-03-20 13:26 UTC, dincho approved these changes

2020-03-20 13:28 UTC, merged